# Generated by Django 5.1.3 on 2024-11-24 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StorageOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneStorageOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cellestial.phone')),
                ('storage_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cellestial.storageoption')),
            ],
        ),
        migrations.AddField(
            model_name='phone',
            name='storage_options',
            field=models.ManyToManyField(through='Cellestial.PhoneStorageOption', to='Cellestial.storageoption'),
        ),
    ]
