# Generated by Django 5.1.3 on 2024-11-28 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cellestial', '0003_product_is_sale_product_sale_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='storage_options',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cellestial.phone'),
        ),
        migrations.RemoveField(
            model_name='phone',
            name='quantity',
        ),
        migrations.AddField(
            model_name='phone',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Cellestial.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='description',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phone',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.ImageField(upload_to='uploads/products/'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='PhoneStorageOption',
        ),
        migrations.DeleteModel(
            name='StorageOption',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
