# Generated by Django 5.1.3 on 2024-12-01 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cellestial', '0010_remove_customuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
