# Generated by Django 5.1.3 on 2024-12-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cellestial', '0012_phone_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='price',
            field=models.IntegerField(default=2500),
        ),
    ]
