# Generated by Django 5.1.3 on 2024-12-07 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cellestial', '0013_storage_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='color',
            field=models.ManyToManyField(to='Cellestial.color'),
        ),
    ]
