# Generated by Django 5.1.3 on 2024-12-08 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cellestial', '0016_remove_color_hex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.PositiveIntegerField(default=7999, max_length=10),
        ),
    ]
