# Generated by Django 5.1.3 on 2024-11-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0002_remove_album_image_alter_album_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, default='none.jpg', upload_to='Assets'),
        ),
        migrations.AlterField(
            model_name='album',
            name='date',
            field=models.DateField(),
        ),
    ]
